backend:
  name: git-gateway
  branch: main # ou "master" selon ton repo

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Auteur", name: "author", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
